### ISSUE TITLE
General Project Setup

### ISSUE THREAD

**Issue by tiscal95** [lukasseiwald/MMP3_Buder_Seiwald_Tischhart#6]
https://github.com/AirConsole/airconsole-phaser-example

http://www.wellkanghome.com/phaser_airconsole/

https://github.com/lean/phaser-es6-webpack

**Comment by RainbowBunchie** [comment]
Ich benutz folgendes Repo zum testen: https://github.com/RainbowBunchie/phaser-airconsole-test

**Comment by RainbowBunchie** [comment]
to do: bisherigen stand in dieses repo ziehen https://github.com/RainbowBunchie/phaser-airconsole-test
