### ISSUE TITLE
Deselect Button screen bug

### ISSUE THREAD

**Issue by lukasseiwald** [lukasseiwald/MMP3_Buder_Seiwald_Tischhart#80]
wenn character ausgewählt und DESELECT BUTTON erscheint, kann man mit unsichtbaren pfeil tasten weiter, dies kann zu mehr bugs fführen wenn user dann einen anderen character auswählt während er noch den anderen character hat.

**Comment by RainbowBunchie** [comment]
pointer events einfach auf none setzen wenn pfeile ausgeblendet
