### ISSUE TITLE
sounds auf eigenem gerät abspielen???? (wie bei nintendo)

### ISSUE THREAD

**Issue by RainbowBunchie** [lukasseiwald/MMP3_Buder_Seiwald_Tischhart#93]

**Comment by lukasseiwald** [comment]
- [x] Sound bei Character Selection wird schon am Handy abgespielt
- [x] Gewinn Sound wird beim Handy abgespielt das die Runde gewinnt
- [ ] Sound wenn hurt, ....

**Comment by RainbowBunchie** [comment]
sound für seele zurück in base bringen auf controller
