### ISSUE TITLE
links/rechts button mehr schräg machen -> also damit daumen besser erreicht 

### ISSUE THREAD

**Issue by RainbowBunchie** [lukasseiwald/MMP3_Buder_Seiwald_Tischhart#96]
foto!

**Comment by RainbowBunchie** [comment]
links und rechts buttons -> in der mitte eine deadzone wo sich der character nicht bewegt!

**Comment by RainbowBunchie** [comment]
![Foto 24 05 19, 14 35 46](https://user-images.githubusercontent.com/16517335/58419546-346ed900-808b-11e9-813c-b6107fdcdec9.jpg)
![Uploading Foto 24.05.19, 14 38 01.jpg…]()

**Comment by RainbowBunchie** [comment]
@RainbowBunchie buttons in illustrator machen
@tiscal95 einbauen

**Comment by lukasseiwald** [comment]
![9242b820-2608-452c-a632-658e4233b7f5](https://user-images.githubusercontent.com/32638146/58469519-f1bb0880-813f-11e9-8716-ab5ab24495de.jpg)

**Comment by RainbowBunchie** [comment]
Bilder als svg in assets/images/controller/buttons-neu/*.svg

bitte einfach bei mir melden wenn was ned passt
