### ISSUE TITLE
aufladen vom schuss irgendwie anzeigen

### ISSUE THREAD

**Issue by RainbowBunchie** [lukasseiwald/MMP3_Buder_Seiwald_Tischhart#98]

**Comment by lukasseiwald** [comment]
eventuell einen kleinen hellen kreis, ähnlich wie da: https://steemitimages.com/p/2gsjgna1uruvUuS7ndh9YqVwYGPLVszbFLwwpAYXZpPARgEnTYwpmSPpw9UAV4Mm8EfQjwjHBpH74bcWZSQVm8HQE8xejFDLf4tEjMdS3AzeKEzjbL?format=match&mode=fit hinter den spieler setzen, der seinen radius verändert mit der auflade zeit und verschwindet wenn kein schuss möglich ist

**Comment by lukasseiwald** [comment]
eventuell einen kleinen hellen kreis, ähnlich wie da: 

![image](https://user-images.githubusercontent.com/32638146/58417456-2027dd80-8085-11e9-8d82-a1a198ea794f.png)

hinter den spieler setzen, der seinen radius verändert mit der auflade zeit und verschwindet wenn kein schuss möglich ist
